import datetime
from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, JSON, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.session import Base

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    phone_number = Column(String, unique=True, index=True, nullable=False)
    password_hash = Column(String, nullable=False)
    role = Column(String, default="viewer", nullable=False)  # "owner" or "viewer"
    is_auto_scanning = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=func.now(), nullable=False)

    portfolios = relationship("Portfolio", back_populates="user", cascade="all, delete-orphan")

class OTPRequest(Base):
    __tablename__ = "otp_requests"

    id = Column(Integer, primary_key=True, index=True)
    phone_number = Column(String, index=True, nullable=False)
    otp_code = Column(String, nullable=False)
    expires_at = Column(DateTime, nullable=False)
    created_at = Column(DateTime, default=func.now(), nullable=False)

class Portfolio(Base):
    __tablename__ = "portfolios"

    id = Column(String, primary_key=True, index=True)  # String UUID generated by frontend or backend
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    name = Column(String, nullable=False)
    symbol = Column(String, nullable=False)
    description = Column(String, nullable=True)
    legs = Column(JSON, nullable=False)  # Storing list of legs as JSON
    createdAt = Column(String, nullable=True)
    marginDeployed = Column(Float, default=0.0)
    realizedPnL = Column(Float, default=0.0)
    entrySpot = Column(Float, default=0.0)
    peakProfit = Column(Float, default=0.0)
    maxDrawdown = Column(Float, default=0.0)
    takeProfit = Column(Float, default=20.0)
    stopLoss = Column(Float, default=0.0)

    user = relationship("User", back_populates="portfolios")


class AlertRule(Base):
    __tablename__ = "alert_rules"

    id = Column(String, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    strategy_type = Column(String, nullable=False)  # e.g., "IRON CONDOR", "1:3:2 CALL RATIO FLY"
    symbol = Column(String, default="ALL")
    expiry = Column(String, default="ALL")
    min_pop = Column(Float, default=0.0)
    min_rr = Column(Float, default=0.0)
    min_loss = Column(Float, nullable=True)
    max_loss = Column(Float, default=1000.0)
    min_delta = Column(Float, nullable=True)
    max_delta = Column(Float, nullable=True)
    min_theta = Column(Float, nullable=True)
    max_gamma = Column(Float, nullable=True)
    active = Column(Boolean, default=True)
    auto_execute = Column(Boolean, default=False)
    take_profit = Column(Float, default=20.0, nullable=True)
    stop_loss = Column(Float, default=0.0, nullable=True)
    created_at = Column(DateTime, default=func.now())

    user = relationship("User")


class TriggeredAlert(Base):
    __tablename__ = "triggered_alerts"

    id = Column(String, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    symbol = Column(String, nullable=False)
    strategy_name = Column(String, nullable=False)
    expiry = Column(String, nullable=False)
    pop = Column(Float, nullable=False)
    max_profit = Column(String, nullable=False)
    max_loss = Column(String, nullable=False)
    rr_ratio = Column(Float, nullable=False)
    timestamp = Column(String, nullable=False)
    current_pnl = Column(String, default="₹0.00")
    spot_price = Column(Float, nullable=True)
    legs = Column(JSON, nullable=False)
    rule_id = Column(String, nullable=True)
    created_at = Column(DateTime, default=func.now())

    user = relationship("User")
